### ISSUE TITLE
Query: Process metadynamics output generated via NAMD COLVAR module

### ISSUE THREAD

**Issue by MamtaMohan** [metagui/metagui3#1]
Dear Toni,

Can Metagui process output generated via colvar module (another option to Plumed software).

I would assume currently No.

Does it require changes? If you can guide me I would appreciate it.

Mamta

**Comment by tonigi** [comment]
Hi, I'm not very familiar with colvar's output.  Is it tabulated files (e.g. colvar and hills)? If so, it should be sufficient to add the relevant headers (see eg the DIALA example).

**Comment by MamtaMohan** [comment]
I think you are right. I am going to try. I did not quite follow your comment about example. Could you please tell me where is 'the DIALA example'

**Comment by tonigi** [comment]
I meant https://github.com/metagui/metagui3/tree/master/DEMO_ALA3

**Comment by MamtaMohan** [comment]
Thank you.
